root = "."
tmp_dir = "/tmp/archura-core-air"

[build]
cmd = "go build -o /tmp/archura-core-air/server ./cmd/server"
bin = "/tmp/archura-core-air/server"
include_ext = ["go", "json", "sql"]
exclude_dir = ["vendor"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
delay = 250
stop_on_error = true
send_interrupt = true
kill_delay = "2s"

[log]
main_only = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
