#!/bin/sh
# Bring up the whole local stack for manual testing:
#   Postgres + Go core (with edge auth) + a watched frontend build served by
#   Wrangler, which owns both the app and its API routes on port 8787.
# Prints the frontend URL, then waits on Wrangler. Ctrl-C stops the local stack;
# Postgres is left running for fast restarts. Does not edit ./core — only runs it.
#
#   sh scripts/dev-up.sh          (lives at the repo root: it orchestrates
#                                  core + editor + Worker, not one package)
set -eu
export LC_ALL=C LANG=C

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
av2="$root/archura-editor"
core_dir="$root/core"
pgdata=/tmp/archura-pg
pgport=54329
pidfile=/tmp/archura-dev-pids

child_pids=""
cleaned_up=false

record_pid() {
  child_pids="$child_pids $1"
  printf '%s\n' "$1" >> "$pidfile"
}

stop_recorded_stack() {
  [ -f "$pidfile" ] || return 0
  while IFS= read -r pid; do
    case "$pid" in
      ''|*[!0-9]*) continue ;;
    esac
    command=$(ps -p "$pid" -o command= 2>/dev/null || true)
    case "$command" in
      *"$root"*) kill "$pid" 2>/dev/null || true ;;
    esac
  done < "$pidfile"
  rm -f "$pidfile"
}

cleanup() {
  [ "$cleaned_up" = false ] || return 0
  cleaned_up=true
  [ -n "$child_pids" ] && kill $child_pids 2>/dev/null || true
  lsof -ti :8080 2>/dev/null | xargs kill 2>/dev/null || true
  lsof -ti :9091 2>/dev/null | xargs kill 2>/dev/null || true
  lsof -ti :8787 2>/dev/null | xargs kill 2>/dev/null || true
  lsof -ti :5300 2>/dev/null | xargs kill 2>/dev/null || true
  rm -f "$pidfile"
}
trap cleanup EXIT INT TERM

# Preflight: a half-dead previous stack (stale core holding the metrics port,
# old watchers rewriting dist, or a mismatched service key) breaks the new one.
stop_recorded_stack
# Clean up processes launched by older dev-up.sh versions that predate pidfile.
pgrep -f "$av2/node_modules/.bin/vite build --watch" 2>/dev/null | xargs kill 2>/dev/null || true
pgrep -f "$av2/node_modules/.bin/wrangler dev --port 8787" 2>/dev/null | xargs kill 2>/dev/null || true
lsof -ti :8080 2>/dev/null | xargs kill 2>/dev/null || true
lsof -ti :9091 2>/dev/null | xargs kill 2>/dev/null || true
lsof -ti :8787 2>/dev/null | xargs kill 2>/dev/null || true
lsof -ti :5300 2>/dev/null | xargs kill 2>/dev/null || true
sleep 1
: > "$pidfile"

# --- Postgres ---
# PG_VERSION check: a stale half-cleaned /tmp dir is not a cluster; re-init it
if [ ! -f "$pgdata/PG_VERSION" ]; then
  rm -rf "$pgdata"
  initdb -D "$pgdata" -U postgres --auth=trust >/dev/null
fi
pg_ctl -D "$pgdata" -o "-p $pgport -k /tmp" -l /tmp/archura-pg.log start >/dev/null 2>&1 || true
sleep 2
createdb -h /tmp -p "$pgport" -U postgres archura 2>/dev/null || true

# --- Core keys ---
cd "$core_dir"
admin=$(go run ./cmd/devkeys admin | cut -d= -f2)
service=$(go run ./cmd/devkeys service | cut -d= -f2)

# --- Core (background) ---
DATABASE_URL="postgres://postgres@/archura?host=/tmp&port=$pgport" \
PLATFORM_ADMIN_KEY="$admin" CORE_SERVICE_KEY="$service" \
REQUIRE_EDGE_AUTH=true PORT=8080 ARCHURA_ENV=dev \
CONFIRM_URL_BASE="http://localhost:8787/confirm" \
  go run ./cmd/server > /tmp/core-run.log 2>&1 &
record_pid "$!"

i=0
while [ $i -lt 40 ]; do
  curl -s http://localhost:8080/healthz >/dev/null 2>&1 && break
  sleep 1
  i=$((i + 1))
done
if ! curl -s http://localhost:8080/healthz >/dev/null 2>&1; then
  printf '%s\n' 'Core failed to start; see /tmp/core-run.log' >&2
  exit 1
fi

# --- Worker (wrangler dev against the built app; the funnel lives here) ---
cd "$av2"
if ! npm run build > /tmp/archura-build.log 2>&1; then
  printf '%s\n' 'Frontend build failed; see /tmp/archura-build.log' >&2
  exit 1
fi

# Source changes re-emit dist/ automatically; Wrangler serves the new assets
# and its native live reload refreshes open app pages.
ARCHURA_WATCH=1 "$av2/node_modules/.bin/vite" build --watch > /tmp/archura-watch-app.log 2>&1 &
record_pid "$!"
node "$av2/scripts/build-components.mjs" --watch > /tmp/archura-watch-components.log 2>&1 &
record_pid "$!"

# .dev.vars wires the local Worker to the local core. Regenerated every run
# because the service key is minted fresh above; a hand-made .dev.vars is
# backed up once instead of clobbered.
if [ -f .dev.vars ] && ! grep -q "generated by dev-up.sh" .dev.vars; then
  cp .dev.vars .dev.vars.bak
fi
cat > .dev.vars <<VARS
# generated by dev-up.sh — matches the core started alongside it
CORE_URL=http://localhost:8080
CORE_SERVICE_KEY=$service
# Local links: wrangler dev simulates the prod route host, so the Worker
# needs telling where it actually is (used by siteUrlFor for "open your site")
PUBLIC_ORIGIN=http://localhost:8787
VARS

"$av2/node_modules/.bin/wrangler" dev --port 8787 --live-reload > /tmp/archura-wrangler.log 2>&1 &
wrangler_pid=$!
record_pid "$wrangler_pid"

node "$av2/toy-client/server.mjs" > /tmp/archura-practice-client.log 2>&1 &
record_pid "$!"
i=0
while [ $i -lt 40 ]; do
  curl -s http://localhost:8787/ >/dev/null 2>&1 && break
  sleep 1
  i=$((i + 1))
done
if ! curl -s http://localhost:8787/ >/dev/null 2>&1; then
  printf '%s\n' 'Frontend failed to start; see /tmp/archura-wrangler.log' >&2
  exit 1
fi

printf '%s\n' 'http://localhost:8787/'

# Keep the stack attached to this terminal; Ctrl-C triggers cleanup.
wait "$wrangler_pid"
