import type { CanonicalComponentData } from './canonical.js';

/** One component instance recorded in an artifact's content.components. */
export type EmbedInstance = {
  componentPath: string[];
  tagName: string;
  instanceId: string;
  attributes: Record<string, unknown>;
};

const SKIPPED_ATTRIBUTES = new Set(['id', 'class', 'style']);

/**
 * Pulls one instance's styling + configured traits out of a published
 * artifact, rewritten so they apply to a bare `<tag>` on any page (an embed
 * has no instance id). Two sources, matching how the editor persists styling:
 * - host custom props inlined on the element by transformForDeployment →
 *   a `tag { … }` rule;
 * - CSS rules still targeting `#instanceId` (responsive overrides in media
 *   queries, part rules like `#id [data-part="x"]`) → same rules with the id
 *   selector rewritten to the tag.
 */
export function extractInstanceEmbed(
  artifact: CanonicalComponentData,
  instance: EmbedInstance
): { css: string; traits: Record<string, string> } {
  const { tagName, instanceId } = instance;
  const rules: string[] = [];

  const doc = new DOMParser().parseFromString(artifact.snapshot.html, 'text/html');
  const el = doc.getElementById(instanceId);
  if (el?.getAttribute('style')) {
    const hostProps = [...el.style.cssText.matchAll(/(--[\w-]+)\s*:/g)]
      .map((m) => m[1])
      .map((prop) => `${prop}: ${el.style.getPropertyValue(prop).trim()};`);
    if (hostProps.length > 0) {
      rules.push(`${tagName} { ${hostProps.join(' ')} }`);
    }
  }

  const idSelector = `#${instanceId}`;
  const rewrite = (rule: CSSStyleRule): string | null => {
    if (!rule.selectorText.includes(idSelector)) return null;
    const selector = rule.selectorText.replaceAll(idSelector, tagName);
    return rule.style.cssText.trim() ? `${selector} { ${rule.style.cssText} }` : null;
  };

  const sheet = new CSSStyleSheet();
  try {
    sheet.replaceSync(artifact.snapshot.css);
    for (const rule of sheet.cssRules) {
      if (rule instanceof CSSStyleRule) {
        const rewritten = rewrite(rule);
        if (rewritten) rules.push(rewritten);
      } else if (rule instanceof CSSMediaRule) {
        const inner = [...rule.cssRules]
          .filter((r): r is CSSStyleRule => r instanceof CSSStyleRule)
          .map(rewrite)
          .filter((r): r is string => r !== null);
        if (inner.length > 0) {
          rules.push(`@media ${rule.media.mediaText} { ${inner.join(' ')} }`);
        }
      }
    }
  } catch {
    // Unparseable artifact CSS: fall through with whatever was collected.
  }

  const traits: Record<string, string> = {};
  for (const [name, value] of Object.entries(instance.attributes ?? {})) {
    if (SKIPPED_ATTRIBUTES.has(name) || name.startsWith('data-gjs')) continue;
    if (value === false || value == null) continue;
    traits[name] = value === true ? '' : String(value);
  }

  return { css: rules.join('\n'), traits };
}

/**
 * Emits the per-client embed module: one JS file that imports the shared
 * (immutable) component module, injects the client's styling once per
 * document, and stamps configured traits onto any bare elements already on
 * the page. Publishing overwrites this module, which is what makes an edit
 * live on every embedding page's next load.
 */
export function generateEmbedModule(options: {
  moduleUrl: string;
  tag: string;
  css: string;
  traits: Record<string, string>;
}): string {
  const { moduleUrl, tag, css, traits } = options;
  return `// Generated by Archura — per-client embed module. Do not edit by hand;
// re-publishing from the editor overwrites this file.
import ${JSON.stringify(moduleUrl)};

const TAG = ${JSON.stringify(tag)};
const CSS = ${JSON.stringify(css)};
const TRAITS = ${JSON.stringify(traits, null, 2)};

const styleId = 'archura-embed-' + TAG;
if (CSS && !document.getElementById(styleId)) {
  const style = document.createElement('style');
  style.id = styleId;
  style.textContent = CSS;
  document.head.appendChild(style);
}

for (const el of document.querySelectorAll(TAG)) {
  for (const [name, value] of Object.entries(TRAITS)) {
    if (!el.hasAttribute(name)) el.setAttribute(name, value);
  }
}
`;
}
